{% set version = "1.9.1" %}

package:
  name: pkginfo
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pkginfo/pkginfo-{{ version }}.tar.gz
  sha256: 4955f1c299e374ccb918dd895c0328d67599bad836dfda2b4639148a113dafec

build:
  noarch: python
  number: 0
  entry_points:
    - pkginfo = pkginfo.commandline:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - pkginfo
    - pkginfo.tests
  commands:
    - pip check
    - pkginfo --help
  requires:
    - pip

about:
  home: https://code.launchpad.net/~tseaver/pkginfo/trunk
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Query metadatdata from sdists / bdists / installed packages.
  description: |
    This package provides an API for querying the distutils metadata written in
    the ``PKG-INFO`` file inside a source distriubtion (an ``sdist``) or
    a binary distribution (e.g., created by running ``bdist_egg``)
  doc_url: http://pythonhosted.org/pkginfo/
  dev_url: https://code.launchpad.net/~tseaver/pkginfo/trunk

extra:
  recipe-maintainers:
    - jakirkham
    - jankatins
    - mingwandroid
